pub use catalogs::*;
pub use credentials::*;
pub use error::*;
pub use external_locations::*;
pub use functions::*;
pub use providers::*;
pub use recipients::*;
pub use schemas::*;
pub use shares::*;
pub use tables::*;
pub use tag_policies::*;
pub use temporary_credentials::*;
pub use volumes::*;

// The aggregate root client (`UnityCatalogClient`) and all request builders are generated by
// trestle under `crate::codegen` (see `codegen/client.rs`). Re-export them at the crate root so
// `unitycatalog_client::UnityCatalogClient` and the `*Builder` types remain the public surface.
pub use crate::codegen::UnityCatalogClient;
pub use crate::codegen::catalogs::builders::{CreateCatalogBuilder, UpdateCatalogBuilder};
pub use crate::codegen::credentials::builders::{CreateCredentialBuilder, UpdateCredentialBuilder};
pub use crate::codegen::entity_tag_assignments::builders::{
    CreateEntityTagAssignmentBuilder, UpdateEntityTagAssignmentBuilder,
};
pub use crate::codegen::external_locations::builders::{
    CreateExternalLocationBuilder, UpdateExternalLocationBuilder,
};
pub use crate::codegen::functions::builders::{
    CreateFunctionBuilder, DeleteFunctionBuilder, GetFunctionBuilder, ListFunctionsBuilder,
    UpdateFunctionBuilder,
};
pub use crate::codegen::providers::builders::{CreateProviderBuilder, UpdateProviderBuilder};
pub use crate::codegen::recipients::builders::{CreateRecipientBuilder, UpdateRecipientBuilder};
pub use crate::codegen::schemas::builders::{CreateSchemaBuilder, UpdateSchemaBuilder};
pub use crate::codegen::shares::builders::{CreateShareBuilder, UpdateShareBuilder};
pub use crate::codegen::tables::builders::CreateTableBuilder;
pub use crate::codegen::tag_policies::builders::{CreateTagPolicyBuilder, UpdateTagPolicyBuilder};
pub use crate::codegen::temporary_credentials::builders::{
    GenerateTemporaryPathCredentialsBuilder, GenerateTemporaryTableCredentialsBuilder,
    GenerateTemporaryVolumeCredentialsBuilder,
};
pub use crate::codegen::volumes::builders::{CreateVolumeBuilder, UpdateVolumeBuilder};

mod catalogs;
pub mod codegen;
mod credentials;
pub mod error;
mod external_locations;
mod functions;
mod providers;
mod recipients;
mod schemas;
mod shares;
mod tables;
mod tag_policies;
mod temporary_credentials;
mod utils;
mod volumes;

impl UnityCatalogClient {
    /// Ergonomic accessor for the temporary credential vending client.
    ///
    /// Wraps the generated low-level client with the hand-written name → UUID resolving helpers
    /// (`temporary_table_credential`, `temporary_volume_credential`, `temporary_path_credential`).
    pub fn temporary_credentials(&self) -> TemporaryCredentialClient {
        TemporaryCredentialClient::new(self.temporary_credentials_client())
    }
}
