repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.2.0"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.35.5
    hooks:
      - id: typos
