repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.2.0"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.35.5
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      # - id: clippy
