version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/googleapis/googleapis
  override:
    - file_option: go_package_prefix
      value: github.com/delta-incubator/delta-sharing-rs/go
plugins:
  - remote: buf.build/community/google-gnostic-openapi:v0.7.0
    out: openapi/sharing-gen
