/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NapiCatalogClient {
  get(includeBrowse?: boolean | undefined | null): Promise<Buffer>
  update(owner?: string | undefined | null, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null, newName?: string | undefined | null): Promise<Buffer>
  delete(force?: boolean | undefined | null): Promise<void>
}

export declare class NapiCredentialClient {
  get(): Promise<Buffer>
  update(newName?: string | undefined | null, comment?: string | undefined | null, readOnly?: boolean | undefined | null, owner?: string | undefined | null, skipValidation?: boolean | undefined | null, force?: boolean | undefined | null): Promise<Buffer>
  delete(): Promise<void>
}

export declare class NapiExternalLocationClient {
  get(): Promise<Buffer>
  update(url?: string | undefined | null, credentialName?: string | undefined | null, readOnly?: boolean | undefined | null, owner?: string | undefined | null, comment?: string | undefined | null, newName?: string | undefined | null, force?: boolean | undefined | null, skipValidation?: boolean | undefined | null): Promise<Buffer>
  delete(force?: boolean | undefined | null): Promise<void>
}

export declare class NapiFunctionClient {
  get(): Promise<Buffer>
  update(owner?: string | undefined | null): Promise<Buffer>
  delete(force?: boolean | undefined | null): Promise<void>
}

export declare class NapiRecipientClient {
  get(): Promise<Buffer>
  update(newName?: string | undefined | null, owner?: string | undefined | null, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null, expirationTime?: number | undefined | null): Promise<Buffer>
  delete(): Promise<void>
}

export declare class NapiSchemaClient {
  get(): Promise<Buffer>
  update(comment?: string | undefined | null, properties?: Record<string, string> | undefined | null, newName?: string | undefined | null): Promise<Buffer>
  delete(force?: boolean | undefined | null): Promise<void>
}

export declare class NapiShareClient {
  get(includeSharedData?: boolean | undefined | null): Promise<Buffer>
  update(newName?: string | undefined | null, owner?: string | undefined | null, comment?: string | undefined | null): Promise<Buffer>
  delete(): Promise<void>
}

export declare class NapiTableClient {
  get(includeDeltaMetadata?: boolean | undefined | null, includeBrowse?: boolean | undefined | null, includeManifestCapabilities?: boolean | undefined | null): Promise<Buffer>
  delete(): Promise<void>
}

export declare class NapiTemporaryCredentialClient {

}

export declare class NapiUnityCatalogClient {
  static fromUrl(baseUrl: string, token?: string | undefined | null): NapiUnityCatalogClient
  listCatalogs(maxResults?: number | undefined | null): Promise<Array<Buffer>>
  listCatalogsStream(maxResults?: number | undefined | null): ReadableStream<Buffer>
  createCatalog(name: string, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null, storageRoot?: string | undefined | null, providerName?: string | undefined | null, shareName?: string | undefined | null): Promise<Buffer>
  listCredentials(purpose?: number | undefined | null, maxResults?: number | undefined | null): Promise<Array<Buffer>>
  listCredentialsStream(purpose?: number | undefined | null, maxResults?: number | undefined | null): ReadableStream<Buffer>
  createCredential(name: string, purpose: number, comment?: string | undefined | null, readOnly?: boolean | undefined | null, skipValidation?: boolean | undefined | null): Promise<Buffer>
  listExternalLocations(maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): Promise<Array<Buffer>>
  listExternalLocationsStream(maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): ReadableStream<Buffer>
  createExternalLocation(name: string, url: string, credentialName: string, readOnly?: boolean | undefined | null, comment?: string | undefined | null, skipValidation?: boolean | undefined | null): Promise<Buffer>
  listFunctions(catalogName: string, schemaName: string, maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): Promise<Array<Buffer>>
  listFunctionsStream(catalogName: string, schemaName: string, maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): ReadableStream<Buffer>
  createFunction(name: string, catalogName: string, schemaName: string, dataType: string, fullDataType: string, parameterStyle: number, isDeterministic: boolean, sqlDataAccess: number, isNullCall: boolean, securityType: number, routineBody: number, routineDefinition?: string | undefined | null, routineBodyLanguage?: string | undefined | null, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null): Promise<Buffer>
  listRecipients(maxResults?: number | undefined | null): Promise<Array<Buffer>>
  listRecipientsStream(maxResults?: number | undefined | null): ReadableStream<Buffer>
  createRecipient(name: string, authenticationType: number, owner: string, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null, expirationTime?: number | undefined | null): Promise<Buffer>
  listSchemas(catalogName: string, maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): Promise<Array<Buffer>>
  listSchemasStream(catalogName: string, maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): ReadableStream<Buffer>
  createSchema(name: string, catalogName: string, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null): Promise<Buffer>
  listShares(maxResults?: number | undefined | null): Promise<Array<Buffer>>
  listSharesStream(maxResults?: number | undefined | null): ReadableStream<Buffer>
  createShare(name: string, comment?: string | undefined | null): Promise<Buffer>
  listTables(catalogName: string, schemaName: string, maxResults?: number | undefined | null, includeDeltaMetadata?: boolean | undefined | null, omitColumns?: boolean | undefined | null, omitProperties?: boolean | undefined | null, omitUsername?: boolean | undefined | null, includeBrowse?: boolean | undefined | null, includeManifestCapabilities?: boolean | undefined | null): Promise<Array<Buffer>>
  listTablesStream(catalogName: string, schemaName: string, maxResults?: number | undefined | null, includeDeltaMetadata?: boolean | undefined | null, omitColumns?: boolean | undefined | null, omitProperties?: boolean | undefined | null, omitUsername?: boolean | undefined | null, includeBrowse?: boolean | undefined | null, includeManifestCapabilities?: boolean | undefined | null): ReadableStream<Buffer>
  createTable(name: string, schemaName: string, catalogName: string, tableType: number, dataSourceFormat: number, storageLocation?: string | undefined | null, comment?: string | undefined | null, properties?: Record<string, string> | undefined | null): Promise<Buffer>
  listVolumes(catalogName: string, schemaName: string, maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): Promise<Array<Buffer>>
  listVolumesStream(catalogName: string, schemaName: string, maxResults?: number | undefined | null, includeBrowse?: boolean | undefined | null): ReadableStream<Buffer>
  createVolume(catalogName: string, schemaName: string, name: string, volumeType: number, storageLocation?: string | undefined | null, comment?: string | undefined | null): Promise<Buffer>
  catalog(name: string): NapiCatalogClient
  credential(name: string): NapiCredentialClient
  externalLocation(name: string): NapiExternalLocationClient
  function(catalogName: string, schemaName: string, functionName: string): NapiFunctionClient
  recipient(name: string): NapiRecipientClient
  schema(catalogName: string, schemaName: string): NapiSchemaClient
  share(name: string): NapiShareClient
  table(name: string): NapiTableClient
  volume(catalogName: string, schemaName: string, volumeName: string): NapiVolumeClient
}

export declare class NapiVolumeClient {
  get(includeBrowse?: boolean | undefined | null): Promise<Buffer>
  update(newName?: string | undefined | null, comment?: string | undefined | null, owner?: string | undefined | null): Promise<Buffer>
  delete(): Promise<void>
}

export interface ClientConfig {
  userAgent?: string
  retryConfig?: RetryConfig
  timeoutConfig?: TimeoutConfig
  extraHeaders?: Record<string, string>
}

/** Retry configuration for the remote HTTP client. */
export interface RetryConfig {
  /**
   * The maximum number of retries for a request. Default is 3. You can also
   * set this via the environment variable `UC_MAX_RETRIES`.
   */
  retries?: number
  /**
   * The maximum number of retries for connection errors. Default is 3. You
   * can also set this via the environment variable `UC_CONNECT_RETRIES`.
   */
  connectRetries?: number
  /**
   * The maximum number of retries for read errors. Default is 3. You can also
   * set this via the environment variable `UC_READ_RETRIES`.
   */
  readRetries?: number
  /**
   * The backoff factor to apply between retries. Default is 0.25. Between each retry
   * the client will wait for the amount of seconds:
   * `{backoff factor} * (2 ** ({number of previous retries}))`. So for the default
   * of 0.25, the first retry will wait 0.25 seconds, the second retry will wait 0.5
   * seconds, the third retry will wait 1 second, etc.
   *
   * You can also set this via the environment variable
   * `UC_RETRY_BACKOFF_FACTOR`.
   */
  backoffFactor?: number
  /**
   * The jitter to apply to the backoff factor, in seconds. Default is 0.25.
   *
   * A random value between 0 and `backoff_jitter` will be added to the backoff
   * factor in seconds. So for the default of 0.25 seconds, between 0 and 250
   * milliseconds will be added to the sleep between each retry.
   *
   * You can also set this via the environment variable
   * `UC_RETRY_BACKOFF_JITTER`.
   */
  backoffJitter?: number
  /**
   * The HTTP status codes for which to retry the request. Default is
   * [429, 500, 502, 503].
   *
   * You can also set this via the environment variable
   * `UC_RETRY_STATUSES`. Use a comma-separated list of integers.
   */
  statuses?: Array<number>
}

/** Timeout configuration for remote HTTP client. */
export interface TimeoutConfig {
  /**
   * The timeout for establishing a connection in seconds. Default is 120
   * seconds (2 minutes). This can also be set via the environment variable
   * `UC_CONNECT_TIMEOUT`, as an integer number of seconds.
   */
  connectTimeout?: number
  /**
   * The timeout for reading data from the server in seconds. Default is 300
   * seconds (5 minutes). This can also be set via the environment variable
   * `UC_READ_TIMEOUT`, as an integer number of seconds.
   */
  readTimeout?: number
  /**
   * The timeout for keeping idle connections in the connection pool in seconds.
   * Default is 300 seconds (5 minutes). This can also be set via the
   * environment variable `UC_CONNECTION_TIMEOUT`, as an integer
   * number of seconds.
   */
  poolIdleTimeout?: number
}
