name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1
  