name: dev

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  typos:
    name: spell-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check spelling
        uses: crate-ci/typos@v1
